home page
Sir-Ob-00/abi_kitchen_app pull request #1
Opened 2024-10-18 13:15 UTC by Sir-Ob-00

Please review my code for me.

2024-10-21 16:04 UTC, gogurlbaby commented
### Required Changes ♻️

Hi @Sir-Ob-00.

Good job so far!
There are some issues that you still need to work on to go to the next task but you are almost there!

![159483175-2f61461d-b352-4cb4-98f8-b173e05ab5ff](https://github.com/user-attachments/assets/b3fc9a9c-eae4-4edf-8e18-b748cc6ae8c2)

### Highlights

✔️ Correct File Structure

### Required

- [ ] _Check the comments under the review._

### Optional Suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@gogurlbaby ] in your question so I can receive the notification.

**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**

2024-10-21 18:03 UTC, gogurlbaby commented
**### Apply These Changes Effectively**

### Comments

1. Use comments to describe what you are working on and also to differentiate sections.
Eg.  
 ` <!-- Navbar Section-->`
  `<!-- Hero Section-->`

### Navbar Section

2. Consider using the same **navbar** for both desktop and mobile, not separately. Challenge yourself to do something like that. That will also help in reducing the codes and making it more re-usable.

3. Not necessary to implement an orders nav item on the navbar. Its okay if you have it displayed on the menu items on the menu page. You can take that out.
`<a href="#" class="py-4 px-2 text-gray-700 hover:text-red-400 underline-hover flex items-center">
            Orders
  <i class="fas fa-chevron-down ml-2 text-sm"></i>
 </a>`

4. For the reservation nav item, take out the dropdown options you have. They can be implemented on the reservation page, but not on the navbar.

__Suggestion:_
Anytime you use an underline feature for a nav-item with a dropdown, it should cover for both the nav-item and the dropdown not separately. This is for next time when you implement something like that_

**Overrall the navbar looks good. Well done!**

### Hero Section

5. I would love you to implement the below image as just the hero section and make it more nicer.

<img width="1440" alt="Screenshot 2024-10-21 at 5 24 46 PM" src="https://github.com/user-attachments/assets/656ac2ca-61b4-4715-80e3-1da536706acc">

- Take out: Where Tradition Meets Taste and Discounts are assured on all ordered dishes.

- Let the section that holds the carousel(slider of images) and text span (cover) for the section.

- You can use: Where Tradition Meets Taste and Discounts are assured on all ordered dishes as description after the title of the hero section. 

- The title and description should be short, concise and catchy.

- Add a CTA(Call to Action) button as well below the description.

### Menu Section

6. Use this below image as the menu section for the home page. 
   Its good to wet the appetite of your users/customers before they move to the menu page itself:

<img width="1440" alt="Screenshot 2024-10-21 at 5 25 12 PM" src="https://github.com/user-attachments/assets/083397a8-62e5-4135-9564-0e4fa0853cfd">

You can use the **VIew Menu Button** but take out the **Book Table** button.

### Reservation Section

7. Create a small section for the reservation to inform users to move to the reservation page. 

- In this case, move the Book Table button here. Make it **Book Now** instead. 

- You can have a a small image or icon with a simple text about the reservation and the book now button.

### Locate Us Section

8. If you are using the google maps section to help users know the location of the restaurant then I suggest you create a nice 
and small **locate us page** on the home page and then add the map. If not take it out because it does not look appealing.

### Footer Section

9. I would suggest you use a background color for the footer instead of a background image. It does not look appealing.

    Make it very simple and readable.

2024-10-21 18:14 UTC, gogurlbaby requested changes
Kindly make the above changes ASAP so we move on to the next step. All the best!!

2024-10-21 18:14 UTC, gogurlbaby commented on home.html
>      <style>
- [ OPTIONAL ] Consider using CSS variables (custom properties) to define colors, font families, and other common values. This can make it easier to update the styling of your website globally.
 
 This is just a suggestion in case you decide to use vanilla css in a project. But its okay for this since you are using tailwind. Well done!
sample:

```
/* Define CSS variables for colors */
:root {
    --primary-color: #21243D;
    --button-background: #FF6464;
    --button-border: #FF6464;
    --button-text: #FFF;
}

/* Rest of your CSS styles */
.title {
    color: var(--primary-color);
    /* ...other styles... */
}

.hero-btn {
    border-radius: 2px;
    background: var(--button-background);
    border: 1px solid var(--button-border);
    color: var(--button-text);
    /* ...other styles... */
}
```

**you can read more about that [here](https://www.freecodecamp.org/news/what-are-css-variables-and-how-to-use-them/)**

2024-10-21 18:14 UTC, gogurlbaby commented on home.html
>      const menu = document.getElementById('mobile-menu');
Move the javascript section to a separate file and link it to the html file.

Check the hamburger menu, its not visible on mobile and not functioning.

Try to correct it. If you have any difficulty, let me know.

2024-10-21 18:14 UTC, gogurlbaby commented on home.html
> +    //JS for slide
Same goes for this:

Move the javascript section to a separate file and link it to the html file.

2024-10-21 18:49 UTC, Sir-Ob-00 commented
Received. Thank you boss

On Mon, Oct 21, 2024, 18:14 Philia Hammond ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Kindly make the above changes ASAP so we move on to the next step. All the
> best!!
> ------------------------------
>
> In home.html
> <https://github.com/Sir-Ob-00/abi_kitchen_app/pull/1#discussion_r1809117126>
> :
>
> > @@ -4,7 +4,7 @@
>      <meta charset="UTF-8">
>      <meta name="viewport" content="width=device-width, initial-scale=1.0">
>      <title>Abi's Kitchen</title>
> -    <link rel="shortcut icon" type="image/png" href="logo.png">
> +    <link rel="shortcut icon" type="image/png" href="/images/background/logo.png">
>      <script src="https://cdn.tailwindcss.com"></script>
>      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
>      <style>
>
>
>    - [ OPTIONAL ] Consider using CSS variables (custom properties) to
>    define colors, font families, and other common values. This can make it
>    easier to update the styling of your website globally.
>
> This is just a suggestion in case you decide to use vanilla css in a
> project. But its okay for this since you are using tailwind. Well done!
> sample:
>
> /* Define CSS variables for colors */
> :root {
>     --primary-color: #21243D;
>     --button-background: #FF6464;
>     --button-border: #FF6464;
>     --button-text: #FFF;
> }
>
> /* Rest of your CSS styles */
> .title {
>     color: var(--primary-color);
>     /* ...other styles... */
> }
>
> .hero-btn {
>     border-radius: 2px;
>     background: var(--button-background);
>     border: 1px solid var(--button-border);
>     color: var(--button-text);
>     /* ...other styles... */
> }
>
> *you can read more about that here
> <https://www.freecodecamp.org/news/what-are-css-variables-and-how-to-use-them/>*
> ------------------------------
>
> In home.html
> <https://github.com/Sir-Ob-00/abi_kitchen_app/pull/1#discussion_r1809200774>
> :
>
> > @@ -345,6 +345,7 @@ <h3 class="text-lg font-bold mb-4 font-bold text-orange-600 bg-white w-28 p-2 ro
>      </footer>
>
>      <script>
> +        //JS for Humburger Menu
>          // Toggle mobile menu visibility
>  document.getElementById('hamburger-button').addEventListener('click', function () {
>      const menu = document.getElementById('mobile-menu');
>
> Move the javascript section to a separate file and link it to the html
> file.
>
> Check the hamburger menu, its not visible on mobile and not functioning.
>
> Try to correct it. If you have any difficulty, let me know.
> ------------------------------
>
> In home.html
> <https://github.com/Sir-Ob-00/abi_kitchen_app/pull/1#discussion_r1809201600>
> :
>
> > @@ -380,7 +381,7 @@ <h3 class="text-lg font-bold mb-4 font-bold text-orange-600 bg-white w-28 p-2 ro
>  });
>
>
> -
> +    //JS for slide
>
> Same goes for this:
>
> Move the javascript section to a separate file and link it to the html
> file.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Sir-Ob-00/abi_kitchen_app/pull/1#pullrequestreview-2382602188>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BJH54DURRLJLBSHTMKUITE3Z4U777AVCNFSM6AAAAABQF57OP6VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDGOBSGYYDEMJYHA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-10-21 19:52 UTC, Sir-Ob-00 commented on home.html
>      <style>
ok

2024-10-22 23:26 UTC, gogurlbaby commented on home.html
> +            <!--Nav:With hero section-->
Your navbar looks separate from your hero so do not make comment as if its together. Your navbar has a visible height which separates it from the hero section.

2024-10-22 23:50 UTC, gogurlbaby commented
The below image is what I mean by the section should span or cover.

See how the sections comes with the background-color spans and the cards are on the background. Do same with the menu section on the home.

<img width="1440" alt="Screenshot 2024-10-22 at 11 46 52 PM" src="https://github.com/user-attachments/assets/dfe34d73-a10e-46f2-b631-9892e8a8ca54">

2024-10-23 00:02 UTC, gogurlbaby requested changes
Good in trying to make changes ASAP. You didn't finish making all changes. Try finishing all and the new changes

2024-10-23 00:02 UTC, gogurlbaby commented on home.html
> +                        <a href="#" class="py-4 px-2 text-gray-700 hover:text-red-400 underline-hover flex items-center">Orders</a>
Take out Order completely from the nav-items. It is on the menu page as a button which is perfect.

2024-10-23 00:02 UTC, gogurlbaby commented on home.html
> +                        <a href="#" class="py-4 px-2 text-gray-700 hover:text-red-400 underline-hover">Reservation</a>
Take out the dropdown from reservation for mobile. Remember to take order completely from mobile too.

2024-10-23 00:02 UTC, gogurlbaby commented on home.html
> +                    <div class="hidden md:flex space-x-6 items-center text-lg">
Try to use same navbar for both desktop and mobile to reduce the codes, they are too much for just a navbar.

Use the hamburger menu for tablet too.

2024-10-23 00:02 UTC, gogurlbaby commented on home.html
> +        <!-- Page Content:Hero Section -->
Very good description using comments. Keep it up!

2024-10-23 00:02 UTC, gogurlbaby commented on home.html
> +                <h1 class="text-5xl font-bold mt-24 mb-8 uppercase">Welcome to Our <span class="text-red-900">Website</span></h1>
Not necessary to welcome users. Take it out.

2024-10-23 00:02 UTC, gogurlbaby commented on home.html
>                        <div class="bg-white flex-shrink-0 w-full flex">
Take out the background-image for the whole page.

The hero section should cover the hero section, there should be no space at the left and right sides.

2024-10-23 00:02 UTC, gogurlbaby commented on home.html
>                              WE SERVE YOU WITH THE BEST LOCAL DISHES
Make the title and description static on the hero page. But the images on the left can be sliding.

Add a CTA button below the description.

2024-10-23 00:02 UTC, gogurlbaby commented on home.html
> +                <!--Picture cards:To Menu Section-->
Add a small description to introduce the menu section before adding the images below it. Let the section cover or span. See extra comment on your PR for more details.

2024-10-23 00:02 UTC, gogurlbaby commented on home.html
> +                <!--View menu button-->
Use your brand colors for the page for the buttons. It should be same for all the buttons and learn to blend them nicely.

Add enough padding on the button.

2024-10-23 00:02 UTC, gogurlbaby commented on home.html
> +    <!--Reservation section-->
You tried with the reservation section but make it more appealing and professional. 

Mind font-size and font-weight for all your texts in the page.

2024-10-23 00:02 UTC, gogurlbaby commented on home.html
>          <!-- Footer Section -->
Take out the background-image. Use a background-color for now. And make it more appealing and creative.

2024-10-23 00:02 UTC, gogurlbaby commented on home.html
>          <!-- Address -->
Do not make the address, navigation etc look like buttons.

2024-10-23 00:02 UTC, gogurlbaby commented on home.html
> +    <script src="/javaScript/home.js">
Very good organisation of your js codes into separate files. You can add it in the head of your html.

2024-10-23 00:02 UTC, gogurlbaby requested changes
Good in trying to make changes ASAP. You didn't finish making all changes. Try finishing all and the new changes.

### **SUBMISSION: WEDNESDAY**

**Immediately reach out if you are not clear about something**

**All the best!!**

2024-10-23 00:06 UTC, gogurlbaby commented on home.html
> +                          <img src="/images/background/logo.png" alt="logo">
No need to use abi's kitchen logo on your hero. You already have it on your navbar. Kindly take it out.

2024-10-23 13:12 UTC, Sir-Ob-00 commented
Okay, thank you!

On Wed, Oct 23, 2024 at 12:06 AM Philia Hammond ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In home.html
> <https://github.com/Sir-Ob-00/abi_kitchen_app/pull/1#discussion_r1811583256>
> :
>
> >                  <div class="relative overflow-hidden">
>                      <div id="slider" class="flex transition-transform duration-500 ease-in-out">
>                        <!-- Slide 1 -->
>                        <div class="bg-white flex-shrink-0 w-full flex">
>                          <div class="block h-full w-2/5 ml-20">
> -                          <img src="logo.png" alt="logo">
> +                          <img src="/images/background/logo.png" alt="logo">
>
> No need to use abi's kitchen logo on your hero. You already have it on
> your navbar. Kindly take it out.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Sir-Ob-00/abi_kitchen_app/pull/1#pullrequestreview-2386613837>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BJH54DSDNS67INXH7QO6OYDZ43SBTAVCNFSM6AAAAABQF57OP6VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDGOBWGYYTGOBTG4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-11-02 19:04 UTC, merged